### ISSUE TITLE
Enum constructor `__` not available from `*.kiss` files.

### ISSUE THREAD

**Issue by 0b1kn00b** [NQNStudios/kisslang#166] opened 2022-10-11 13:06 UTC
I have an enum

```haxe
enum Wildcard{
__;
}
```
That I use to attach static extensions as an ersatz global. It's not available, and I'm not sure why.
Using the old build style, I could go;

```haxe
using stx.Nano;
final _ = __;
```

but without the final, kiss wouldn't recognise it. Any idea?

**Comment by NQNStudios** [comment] 2022-10-11 18:03
I'm guessing you have the enum declaration in a `Wildcard.hx` Haxe file, and a Kiss file that looks like this:

Example.kiss
```
(using stx.Nano)
(var _ __)
```

Is that correct? This is how I put together my code to reproduce the bug.

If so, `__` is an unknown identifier because your kiss file needs to have `(import Wildcard)` to access the `__` constructor.

Now, your _ variable should be accessible within Example.kiss. However it will be private to Example, because I have kiss make `_varname` private and `varname` public to shorten typing `public` and `private` all the time. If you want `_` to be public you would write `(var &public _ __)`.

**Comment by NQNStudios** [comment] 2022-11-09 18:21
Did any of my suggestions provide what you're looking for?

If you want to show me what you're working on with Kiss, I'd be super interested!

**Comment by 0b1kn00b** [comment] 2022-11-09 18:30
Sorry, it got stuck on the back burner while I work on a build tool. 

I'm working on a whole bunch of stuff over at www.github.com/ohmrun. (everything is on the develop branch)

When I get back around I'll be likely declaring schema just, and see where it fits in after that.

**Comment by NQNStudios** [comment] 2022-12-04 20:15
I'm going to close this because I think I answered it. If you come back and my solution doesn't work, you can reopen it later.

**Closed as completed by NQNStudios** 2022-12-04 20:15 UTC
